- name: variables from arguments
  hosts: local
  connection: local  # Ansible is connecting to localhost
  tasks:
  - name: print the courses information
    ansible.builtin.debug:
     msg: "Course is:{{ COURSE }}, duration is:{{ DURATION }},trainer is:{{ TRAINER}}"