- name: variables preferences
  hosts: local
  connection: local
  vars:
   NAME: from play level
  #vars_files:
   # - Course.yaml
  vars_prompt:
  - name: NAME
    prompt: What is you NAME
    private: false
  tasks:
     - name: testing variables preference
      # vars:
       #  NAME: from task level
       ansible.builtin.debug:
         msg: "Name: {{ NAME }}"