- name: variables preferences
  hosts: local
  connection: local  
  vars:
   NAME: from play level
   vars_files:
   - Couse.yaml
   vars_prompt:
      - name: NAME
        prompt: what is you NAME
        private: false
  tasks:
   - name: testing variables preference
     NAME: from task level
     ansible.builtin.debug:
     msg: "Name: {{ NAME }}"
