- name: check the facts
  hosts: local
  connection: local
  become: yes
  tasks: 
   - name: install nginx if redhat
     ansible.builtin.dnf:
       name: nginx
       state: latest
     when: ansible_os_family --"RedHat"  ## use Ansible _while referring the facts
