- name: check the facts
  hosts: local
  connection: local
  tasks: 
   - name: install nginx if redhat os 
     ansible.builtin.dnf:
      name: nginx
      state: latest
     when: ansible_os_family ="RedHat"  ## use Ansible _while referring the facts
